### ISSUE TITLE
Exception thrown when loading original jpeg file shot by ILCE-7RM3

### ISSUE THREAD

**Issue by ldwnt** [SK-Hardwired/s_afv#2]
The exception is thrown when loading original jpeg file (as below) shot by ILCE-7RM3:
[DSC00008.zip](https://github.com/SK-Hardwired/s_afv/files/2053726/DSC00008.zip)

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\matplotlib\cbook\__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\cbook\__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\widgets.py", line 225, in _release
    func(event)
  File "afv.py", line 55, in ofile
    self.start(F)
  File "afv.py", line 1139, in start
    ax.add_patch(focuspoint)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2007, in add_patch
    self._update_patch_limits(p)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2027, in _update_patch_limits
    xys = patch.get_patch_transform().transform(vertices)
  File "C:\Python27\lib\site-packages\matplotlib\patches.py", line 1494, in get_patch_transform
    self._recompute_transform()
  File "C:\Python27\lib\site-packages\matplotlib\patches.py", line 1478, in _recompute_transform
    center = (self.convert_xunits(self.center[0]),
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 191, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "C:\Python27\lib\site-packages\matplotlib\axis.py", line 1526, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "C:\Python27\lib\site-packages\matplotlib\category.py", line 65, in convert
    unit.update(values)
AttributeError: 'NoneType' object has no attribute 'update'

When loading arw files shot by ILCE-7RM3, no exception is thrown, but no picture is shown in UI, either.

**Comment by SK-Hardwired** [comment]
Hi! There is issue with newer Matplotlib (2.1.0 and newer) versions where add_patch command changed or broken. 
Please user matplotlib 2.0.2:
1) Remove old matplotlib with "pip uninstall matplotlib"
2) Install 2.0.2 ver with: "pip install matplotlib==2.0.2"
